import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by next-pwa at build time
    'public/sw.js',
    'public/sw.js.map',
    'public/workbox-*.js',
    'public/workbox-*.js.map',
    'public/fallback-*.js',
  ]),
  {
    rules: {
      // The fetch-in-useEffect pattern is fine for legitimate data loading;
      // this rule is too aggressive for our usage.
      'react-hooks/set-state-in-effect': 'off',
    },
  },
]);

export default eslintConfig;
